name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  intl: ^0.17.0
  simple_animations: ^3.0.0
  flutter_native_splash: ^2.2.6

  sms_autofill: ^2.2.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  flutter_spinwheel: ^0.1.0
  flutter_fortune_wheel: ^1.2.0
  basic_utils: ^4.5.0
  flutter_spinning_wheel: ^1.1.0
  rxdart: ^0.27.5
  vertical_card_pager: ^1.5.0
  font_awesome_flutter: ^10.1.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
